<?php 

$imageArray = array(
    0 => 'victoria.PNG',
    1 => 'PLACEHOLDERPIC2',
    2 => 'PLACEHOLDERPIC3' ,
    3 => 'PLACEHOLDERPIC4',
    4 => 'PLACEHOLDERPIC5',
    5 => 'PLACEHOLDERPIC6',
    6 => 'PLACEHOLDERPIC7' ,
    7 => 'PLACEHOLDERPIC8',
    8 => 'PLACEHOLDERPIC9',
    9 => 'PLACEHOLDERPIC10'
    );
    
    $nameArray = array(
    0 =>'PLACEHOLDERNAME1',
    1 =>'PLACEHOLDERNAME2',
    2 =>'PLACEHOLDERNAME3',
    3 =>'PLACEHOLDERNAME4',
    4 =>'PLACEHOLDERNAME5',
    5 =>'PLACEHOLDERNAME6',
    6 =>'PLACEHOLDERNAME7',
    7 =>'PLACEHOLDERNAME8',
    8 =>'PLACEHOLDERNAME9',
    9 =>'PLACEHOLDERNAME10'
    );
    
    $descriptionArray = array(
    0 => 'PLACEHOLDERDESCRIPTION1',
    1 => 'PLACEHOLDERDESCRIPTION2',
    2 => 'PLACEHOLDERDESCRIPTION3',
    3 => 'PLACEHOLDERDESCRIPTION4',
    4 => 'PLACEHOLDERDESCRIPTION5',
    5 => 'PLACEHOLDERDESCRIPTION6',
    6 => 'PLACEHOLDERDESCRIPTION7',
    7 => 'PLACEHOLDERDESCRIPTION8',
    8 => 'PLACEHOLDERDESCRIPTION9',
    9 => 'PLACEHOLDERDESCRIPTION10'
    );
    $priceArray = array(
    0 => 'PLACEHOLDERPRICE1',
    1 => 'PLACEHOLDERPRICE2',
    2 => 'PLACEHOLDERPRICE3',
    3 => 'PLACEHOLDERPRICE4',
    4 => 'PLACEHOLDERPRICE5',
    5 => 'PLACEHOLDERPRICE6',
    6 => 'PLACEHOLDERPRICE7',
    7 => 'PLACEHOLDERPRICE8',
    8 => 'PLACEHOLDERPRICE9',
    9 => 'PLACEHOLDERPRICE10',    
    );





?>
